[package]
name = "doc-agent"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
ammonia.workspace = true
askama.workspace = true
async-trait.workspace = true
chrono.workspace = true
comrak.workspace = true
croner.workspace = true
futures.workspace = true
reqwest.workspace = true
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

doc-plugin-sdk = { workspace = true, features = ["reqwest"] }
