[package]
name = "doc-software-templates"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
askama.workspace = true
async-trait.workspace = true
base64.workspace = true
chrono.workspace = true
flate2.workspace = true
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml_ng.workspace = true
tar.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

doc-plugin-sdk = { workspace = true, features = ["reqwest"] }
