[package]
name = "doc-grafana"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
askama.workspace = true
async-trait.workspace = true
chrono.workspace = true
hex.workspace = true
regex.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

doc-plugin-sdk.workspace = true
