#!/usr/bin/env bash
# Writes 10-config.yaml from the files the repository already keeps, so the cluster runs the same
# configuration as everything else rather than a copy that drifts.
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
out="$root/deploy/kubernetes/doc-system/10-config.yaml"

indent() { sed 's/^/    /' "$1"; }

{
  cat <<'HEAD'
# The platform's configuration and the database's init scripts, as ConfigMaps.
#
# Generated by deploy/kubernetes/generate-config.sh from the files in the repository. Do not edit
# by hand: run the script again instead.
apiVersion: v1
kind: ConfigMap
metadata:
  name: doc-config
  namespace: doc-system
data:
  doc.toml: |
HEAD
  indent "$root/config/doc.toml"
  echo "  doc-frontend.toml: |"
  indent "$root/config/doc-frontend.toml"
  cat <<'MID'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: doc-system
data:
MID
  for script in "$root"/crates/storage/postgres/init/*.sh; do
    echo "  $(basename "$script"): |"
    indent "$script"
  done
} > "$out"

echo "wrote $out"
